# Generated by Django 2.0.1 on 2018-03-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BK', 'Book'), ('AU', 'Audio')], default='Book', max_length=6)),
                ('genre', models.CharField(max_length=100)),
                ('isbn_number', models.CharField(max_length=13)),
                ('sales', models.IntegerField(default=0)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('document', models.FileField(upload_to='books/')),
                ('book_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='bookimages/')),
                ('audio_file', models.FileField(blank=True, default='', null=True, upload_to='audiofiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('buyer', models.CharField(max_length=100)),
                ('transaction_id', models.AutoField(max_length=90, primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.Book')),
            ],
        ),
    ]
